version: "2.1"
services:
  radarr:
    image: linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Warsaw
      - UMASK_SET=022 #optional
    volumes:
      - ${radarr_config_path}:/config
      - ${movie_path}:/movies
      - ${download_path}:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
        - PUID=1000
        - PGID=1000
        - TZ=Europe/Warsaw
        - UMASK_SET=022 #optional
    volumes:
        - ${sonarr_config_path}:/config
        - ${tv_serries_path}:/tv
        - ${download_path}:/downloads
    ports:
        - 8989:8989
    restart: unless-stopped
  bazarr:
    image: linuxserver/bazarr
    container_name: bazarr
    environment:
        - PUID=1000
        - PGID=1000
        - TZ=Europe/Warsaw
        - UMASK_SET=022 #optional
    volumes:
        - ${bazarr_config_path}:/config
        - ${movie_path}:/movies
        - ${tv_serries_path}:/tv
    ports:
        - 6767:6767
    restart: unless-stopped
  qbittorrent:
    image: linuxserver/qbittorrent
    container_name: qbittorrent
    environment:
        - PUID=1000
        - PGID=1000
        - TZ=Europe/Warsaw
        - UMASK_SET=022
        - WEBUI_PORT=8080
    volumes:
        - ${qbittorrent_config_path}:/config
        - ${download_path}:/downloads
    ports:
        - 6881:6881
        - 6881:6881/udp
        - 8080:8080
    restart: unless-stopped
  jackett:
    image: linuxserver/jackett
    container_name: jackett
    environment:
        - PUID=1000
        - PGID=1000
        - TZ=Europe/Warsaw
        - RUN_OPTS=run options here #optional
    volumes:
        - ${jackett_config_path}:/config
        - ${jacket_download_path}:/downloads
    ports:
        - 9117:9117
    restart: unless-stopped
  jellyfin:
    image: linuxserver/jellyfin
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Warsaw
      - UMASK_SET=022 #optional
    volumes:
      - ${jellyfin_config_path}:/config
      - ${tv_serries_path}:/data/tvshows
      - ${movie_path}:/data/movies
      # - /opt/vc/lib:/opt/vc/lib #optional
    ports:
      - 8096:8096
      - 8920:8920 #optional
    restart: unless-stopped