version: "2.1"
services:
  radarr:
    image: linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Warsaw
      - UMASK_SET=022 #optional
    volumes:
      - ./radarr/config:/config
      - ./radarr/movies:/movies
      - ./qbit/download:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
        - PUID=1000
        - PGID=1000
        - TZ=Europe/Warsaw
        - UMASK_SET=022 #optional
    volumes:
        - ./sonarr/config:/config
        - ./sonarr/shows:/tv
        - ./qbit/download:/downloads
    ports:
        - 8989:8989
    restart: unless-stopped
  bazarr:
    image: linuxserver/bazarr
    container_name: bazarr
    environment:
        - PUID=1000
        - PGID=1000
        - TZ=Europe/Warsaw
        - UMASK_SET=022 #optional
    volumes:
        - ./bazarr/config:/config
        - ./radarr/movies:/movies
        - ./sonarr/shows:/tv
    ports:
        - 6767:6767
    restart: unless-stopped
  qbittorrent:
    image: linuxserver/qbittorrent
    container_name: qbittorrent
    environment:
        - PUID=1000
        - PGID=1000
        - TZ=Europe/Warsaw
        - UMASK_SET=022
        - WEBUI_PORT=8080
    volumes:
        - ./qbit/config:/config
        - ./qbit/download:/downloads
    ports:
        - 6881:6881
        - 6881:6881/udp
        - 8080:8080
    restart: unless-stopped
  jackett:
    image: linuxserver/jackett
    container_name: jackett
    environment:
        - PUID=1000
        - PGID=1000
        - TZ=Europe/Warsaw
        - RUN_OPTS=run options here #optional
    volumes:
        - ./jackett/config:/config
        - ./jackett/downloads:/downloads
    ports:
        - 9117:9117
    restart: unless-stopped